global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'devops-platform'
    replica: 'prometheus-0'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - 节点指标
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metrics_path: /metrics

  # 监控服务
  - job_name: 'monitoring-service'
    static_configs:
      - targets: ['monitoring-service:8000']
    scrape_interval: 10s
    metrics_path: /api/v1/metrics/prometheus

  # 系统指标收集
  - job_name: 'system-metrics'
    static_configs:
      - targets: ['monitoring-service:8000']
    scrape_interval: 10s
    metrics_path: /api/v1/metrics/prometheus