apiVersion: v2
name: devops-monitoring
description: 运维平台监控系统 Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - devops
home: https://github.com/your-org/devops-platform
sources:
  - https://github.com/your-org/devops-platform
maintainers:
  - name: DevOps Team
    email: devops@company.com
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled